name: artifacts-demo

on: push

jobs:
    job_1:
        name: Upload artifact
        runs-on: ubuntu-latest
        steps:
        -   run: echo "hi"
            name: cretae a local file

    job_2:
        name: download artifact
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - uses: actions/doenload-artifacts@v2
              with:
                name: file
            - run: cat file.txt
                


    

