name: Deploy Infra

on: 
    workflow_dispatch: 


jobs:
    Infra-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v4.1.7
        